# Generated by Django 3.0.7 on 2020-07-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_topics_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
    ]
