# Generated by Django 3.0.7 on 2020-07-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200705_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
