# Generated by Django 3.0.7 on 2020-07-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='viewCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
